/***********************************/ 
/** THIS DATABSE IS FOR MARIA DB **/
/*********************************/

DROP TABLE IF EXISTS COUNTRY;

CREATE TABLE COUNTRY (
                ID INT AUTO_INCREMENT PRIMARY KEY,
                COUNTRY VARCHAR(255) NOT NULL,
                COUNTRY_ESP VARCHAR(255) DEFAULT NULL,
                COUNTRY_GER VARCHAR(255) DEFAULT NULL,
                COUNTRY_ITA VARCHAR(255) DEFAULT NULL,
                ISO_ALFA_2 VARCHAR(20) NOT NULL UNIQUE,
                ISO_ALFA_3 VARCHAR(20) NOT NULL UNIQUE,
                ISO_NUMERIC SMALLINT NOT NULL UNIQUE
                );

/*
INSERT INTO THE SAME SQL SERVER 
*/


/********************************/ 
/* THIS DATABSE IS FOR POSTGREESQL **/
/******************************/

CREATE TABLE COUNTRY (
  ID SERIAL PRIMARY KEY,
  COUNTRY VARCHAR(255) NOT NULL,
  COUNTRY_ESP VARCHAR(255) DEFAULT NULL,
  COUNTRY_GER VARCHAR(255) DEFAULT NULL,
  COUNTRY_ITA VARCHAR(255) DEFAULT NULL,
  ISO_ALFA_2 VARCHAR(20) NOT NULL UNIQUE,
  ISO_ALFA_3 VARCHAR(20) NOT NULL UNIQUE,
  ISO_NUMERIC SMALLINT NOT NULL UNIQUE
);


/*
INSERT INTO THE SAME SQL SERVER 
*/