IF(OBJECT_ID('COUNTRY') IS NOT NULL)
                    DROP TABLE COUNTRY

CREATE TABLE COUNTRY (
  ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  COUNTRY VARCHAR(255) NOT NULL,
  COUNTRY_ESP VARCHAR(255) NULL,
  COUNTRY_GER VARCHAR(255) NULL,
  COUNTRY_ITA VARCHAR(255) NULL,
  ISO_ALFA_2 VARCHAR(20) NOT NULL UNIQUE,
  ISO_ALFA_3 VARCHAR(20) NOT NULL UNIQUE,
  ISO_NUMERIC SMALLINT NOT NULL UNIQUE
);



INSERT INTO COUNTRY (COUNTRY, COUNTRY_ESP, COUNTRY_GER, COUNTRY_ITA, ISO_ALFA_2, ISO_ALFA_3, ISO_NUMERIC) VALUES
('Aruba ', 'Aruba', 'Aruba', 'Aruba', 'AW',  'ABW','533'  ),
('Afghanistan', 'Afganistan', 'Afghanistan', 'Afghanistan', 'AF',  'AFG','4'  ),
('Angola', 'Angola', 'Angola', 'Angola', 'AO',  'AGO','24'  ),
('Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'AI',  'AIA','660'  ),
('Aland Islands ', 'Aland', 'Aland', 'Isole Aland', 'AX',  'ALA','248'  ),
('Albania', 'Albania', 'Albanien', 'Albania', 'AL',  'ALB','8'  ),
('Andorra', 'Andorra', 'Andorra', 'Andorra', 'AD',  'AND','20'  ),
('United Arab Emirates', 'Emiratos Arabes Unidos', 'Vereinigte Arabische Emirate', 'Emirati Arabi Uniti', 'AE',  'ARE','784'  ),
('Argentina', 'Argentina', 'Argentinien', 'Argentina', 'AR',  'ARG','32'  ),
('Armenia ', 'Armenia', 'Armenien', 'Armenia', 'AM',  'ARM','51'  ),
('American Samoa', 'Samoa Americana', 'Amerikanisch-Samoa', 'Samoa americane', 'AS',  'ASM','16'  ),
('Antartica ', 'Antartida', 'Antartiks', 'Antartide', 'AQ',  'ATA','10'  ),
('French Southern and Antarctic Lands ', 'Tierras Australes y Antarticas Francesas', 'Französische Sud- und Antarktisgebiete', 'Terre Australi e Antartiche Francesi', 'TF',  'ATF','260'  ),
('Antigua and Barbuda', 'Antigua y Barbuda', 'Antigua und Barbuda', 'Antigua e Barbuda', 'AG',  'ATG','28'  ),
('Australia', 'Australia', 'Australien', 'Australia', 'AU',  'AUS','36'  ),
('Austria', 'Austria', 'Osterreich	', 'Austria', 'AT',  'AUT','40'  ),
('Azerbaijan ', 'Azerbaiyan', 'Aserbaidschan', 'Azerbaigian', 'AZ',  'AZE','31'  ),
('Burundi', 'Burundi', 'Burundi', 'Burundi', 'BI',  'BDI','108'  ),
('Belgium', 'Belgica', 'Belgien', 'Belgio', 'BE',  'BEL','56'  ),
('Benin', 'Benin', 'Benin', 'Benin', 'BJ',  'BEN','204'  ),
('Caribbean Netherlands ', 'Bonaire Sint Eustatius and Saba', 'Karibische Niederlande', 'Paesi Bassi caraibici', 'BQ',  'BES','535'  ),
('Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'BF',  'BFA','854'  ),
('Bangladesh', 'Banglades', 'Bangladesch', 'Bangladesh', 'BD',  'BGD','50'  ),
('Bulgaria', 'Bulgaria', 'Bulgarien', 'Bulgaria', 'BG',  'BGR','100'  ),
('Bahrain', 'Barein', 'Bahrain', 'Bahrein', 'BH',  'BHR','48'  ),
('Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'BS',  'BHS','44'  ),
('Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'Bosnien und Herzegowina', 'Bosnia ed Erzegovina', 'BA',  'BIH','70'  ),
('Saint Barthélemy ', 'San Bartolome', 'Sankt Bartholomaus', 'Collettivita di Saint-Barthelemy', 'BL',  'BLM','652'  ),
('Belarus', 'Bielorrusia', 'Wei russland', 'Bielorussia', 'BY',  'BLR','112'  ),
('Belize', 'Belice', 'Belize', 'Belize', 'BZ',  'BLZ','84'  ),
('Bermuda', 'Bermudas', 'Bermuda', 'Bermude', 'BM',  'BMU','60'  ),
('Bolivia', 'Bolivia', 'Bolivien', 'Bolivia', 'BO',  'BOL','68'  ),
('Brazil', 'Brasil', 'Brasilien', 'Brasile', 'BR',  'BRA','76'  ),
('Barbados', 'Barbados', 'Barbados', 'Barbados', 'BB',  'BRB','52'  ),
('Brunei Darusalaam', 'Brunei', 'Brunei Darusalaam', 'Brunei Darusalaam', 'BN',  'BRN','96'  ),
('Bhutan ', 'Butan', 'Bhutan', 'Butan', 'BT',  'BTN','64'  ),
('Bouvet Island ', 'Isla Bouvet', 'Bouvetinsel', 'Isola Bouvet', 'BV',  'BVT','74'  ),
('Botswana', 'Botsuana', 'Botswana', 'Botswana', 'BW',  'BWA','72'  ),
('Central African Republic', 'Republica Centroafricana', 'Zentralafrikanische Republik', 'Repubblica Centrafricana', 'CF',  'CAF','140'  ),
('Canada', 'Canada', 'Kanada', 'Canada', 'CA',  'CAN','124'  ),
('Cocos Islands', 'Islas Cocos', 'Kokosinseln', 'Isole Coco', 'CC',  'CCK','166'  ),
('Switzerland', 'Suiza', 'Schweiz', 'Svizzera', 'CH',  'CHE','756'  ),
('Chile', 'chile', 'Chile', 'Cile', 'CL',  'CHL','152'  ),
('China', 'China', 'China', 'Cina ', 'CN',  'CHN','156'  ),
('Ivory Coast', 'Costa de Marfil', 'Elfenbeinkste', 'Costa d Avorio ', 'CI',  'CIV','384'  ),
('Cameroon', 'Camerun', 'Kamerun', 'Camerun', 'CM',  'CMR','120'  ),
('Democratic Republic of the Congo ', 'Republica democratica del congo', 'Demokratische Republik Kongo', 'Repubblica Democratica del Congo', 'CD',  'COD','180'  ),
('Congo', 'Republica del Congo', 'Kongo', 'Repubblica Congo', 'CG',  'COG','178'  ),
('Cook Islands', 'Islas Cook', 'Cookinseln', 'Isole Cook', 'CK',  'COK','184'  ),
('Colombia', 'Colombia', 'Kolumbien', 'Colombia', 'CO',  'COL','170'  ),
('Comoros and Mayotte Island', 'Comoras', 'Komoren und Mayotte', 'Isola Comore e Mayotte', 'KM',  'COM','174'  ),
('Cape Verde', 'Cabo Verde', 'Kap Verde', 'Capo Verde', 'CV',  'CPV','132'  ),
('Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'CR',  'CRI','188'  ),
('Cuba', 'cuba', 'Kuba', 'Cuba', 'CU',  'CUB','192'  ),
('Curacao ', 'Curazao', 'Curacao', 'Curacao', 'CW',  'CUW','531'  ),
('Christmas Island', 'Isla de Navidad', 'Weihnachtsinsel', 'Isola di Natale', 'CX',  'CXR','162'  ),
('Cayman Islands', 'Islas Caiman', 'Kaimaninseln', 'Isole Cayman', 'KY',  'CYM','136'  ),
('Cyprus', 'Chipre', 'Zypern', 'Cipro', 'CY',  'CYP','196'  ),
('Czech Republic', 'Republica Checa', 'Tschechische Republik', 'Repubblica Ceca', 'CZ',  'CZE','203'  ),
('Germany', 'Alemania', 'Deutschland', 'Germania', 'DE',  'DEU','276'  ),
('Djibouti', 'Yibuti', 'Dschibuti', 'Gibuti', 'DJ',  'DJI','262'  ),
('Dominica', 'Dominica', 'Dominica', 'Dominica', 'DM',  'DMA','212'  ),
('Denmark', 'Dinamarca', 'Danemark', 'Danimarca', 'DK',  'DNK','208'  ),
('Dominican Republic', 'Republica Dominicana', 'Dominikanische Republik', 'Repubblica Dominicana', 'DO',  'DOM','214'  ),
('Algeria', 'Argelia', 'Algerien', 'Algeria', 'DZ',  'DZA','12'  ),
('Ecuador', 'Ecuador', 'Ecuador', 'Ecuador', 'EC',  'ECU','218'  ),
('Egypt', 'Egipto', 'Agypten', 'Egitto', 'EG',  'EGY','818'  ),
('Eritrea ', 'Eritrea', 'Eritrea', 'Eritrea', 'ER',  'ERI','232'  ),
('Western Sahara', 'Republica arabe Saharaui Democratica', 'Westsahara', 'Sahara Occidentale', 'EH',  'ESH','732'  ),
('Spain', 'Espana', 'Spanien', 'Spagna	', 'ES',  'ESP','724'  ),
('Estonia', 'Estonia', 'Estland', 'Estonia', 'EE',  'EST','233'  ),
('Ethiopia', 'Etiopia', 'Athiopien', 'Etiopia', 'ET',  'ETH','231'  ),
('Finland', 'Finlandia', 'Finnland', 'Finlandia', 'FI',  'FIN','246'  ),
('Fiji', 'Fiyi', 'Fidschi', 'Figi', 'FJ',  'FJI','242'  ),
('Falkland Islands ', 'Islas Malvinas', 'Falklandinseln', 'Isole Falkland', 'FK',  'FLK','238'  ),
('France', 'Francia', 'Frankreich', 'Francia', 'FR',  'FRA','250'  ),
('Faeroe Islands ', 'Islas Feroe', 'Faroer-Insel', 'Isole Faroe', 'FO',  'FRO','234'  ),
('Micronesia', 'Micronesia', 'Mikronesien', 'Micronesia', 'FM',  'FSM','583'  ),
('Gabon', 'Gabon', 'Gabun', 'Gabon', 'GA',  'GAB','266'  ),
('United Kingdom', 'Reino Unido', 'Vereinigtes Konigreich', 'Regno Unito	', 'GB',  'GBR','826'  ),
('Georgia', 'Georgia', 'Georgien', 'Georgia', 'GE',  'GEO','268'  ),
('Guernsey ', 'Guernsey', 'Guernsey', 'Guernsey', 'GG',  'GGY','831'  ),
('Ghana', 'Ghana', 'Ghana', 'Ghana', 'GH',  'GHA','288'  ),
('Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibilterra', 'GI',  'GIB','292'  ),
('Guinea', 'Guinea', 'Guinea', 'Guinea', 'GN',  'GIN','324'  ),
('Guadeloupe ', 'Guadalupe', 'Guadeloupe', 'Guadalupa', 'GP',  'GLP','312'  ),
('Gambia', 'Gambia', 'Gambia', 'Gambia', 'GM',  'GMB','270'  ),
('Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'GW',  'GNB','624'  ),
('Equatorial Guinea', 'Guinea Ecuatorial', 'Aquatorialguinea', 'Guinea Equatoriale', 'GQ',  'GNQ','226'  ),
('Greece', 'Grecia', 'Griechenland', 'Grecia', 'GR',  'GRC','300'  ),
('Grenada', 'Granada', 'Grenada', 'Grenada', 'GD',  'GRD','308'  ),
('Greenland', 'Groenlandia', 'Gronland', 'Groenlandia', 'GL',  'GRL','304'  ),
('Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'GT',  'GTM','320'  ),
('French Guiana', 'Guayana Francesa', 'Franzosisch-Guayana', 'Guyana Francese', 'GF',  'GUF','254'  ),
('Guam', 'Guam', 'Guam', 'Guam', 'GU',  'GUM','316'  ),
('Guyana', 'Guyana', 'Guyana', 'Guyana', 'GY',  'GUY','328'  ),
('Hong Kong', 'Hong Kong', 'Hongkong', 'Hong Kong ', 'HK',  'HKG','344'  ),
('Heard Island and McDonald Islands ', 'Territorio de las Islas Heard y McDonald', 'Heard und McDonaldinseln', 'L isola Heard e le isole McDonald', 'HM',  'HMD','334'  ),
('Honduras', 'Honduras', 'Honduras ', 'Honduras ', 'HN',  'HND','340'  ),
('Croatia', 'Croacia', 'Kroatien', 'Croazia', 'HR',  'HRV','191'  ),
('Haiti', 'Haiti', 'Haiti', 'Haiti', 'HT',  'HTI','332'  ),
('Hungary', 'Hungria', 'Ungarn', 'Ungheria ', 'HU',  'HUN','348'  ),
('Indonesia', 'Indonesia', 'Indonesien', 'Indonesia ', 'ID',  'IDN','360'  ),
('Isle of Man ', 'Isla de Man', 'Insel Man', 'Isola di Man', 'IM',  'IMN','833'  ),
('India', 'India', 'Indien', 'India ', 'IN',  'IND','356'  ),
('British Indian Ocean Territory ', 'Territorio Britanico del Oceano Indico', 'Britisches Territorium im Indischen Ozean', 'Territorio Britannico dell Oceano Indiano', 'IO',  'IOT','86'  ),
('Irish Republic', 'Republica de Irlanda', 'Irische Republik', 'Repubblica Irlandese ', 'IE',  'IRL','372'  ),
('Iran', 'Iran', 'Iran', 'Iran ', 'IR',  'IRN','364'  ),
('Iraq', 'Irak', 'Irak', 'Iraq ', 'IQ',  'IRQ','368'  ),
('Iceland', 'Islandia', 'Island', 'Islanda ', 'IS',  'ISL','352'  ),
('Israel', 'Israel', 'Israel', 'Israele ', 'IL',  'ISR','376'  ),
('Italy', 'Italia', 'Italien', 'Italia ', 'IT',  'ITA','380'  ),
('Jamaica', 'Jamaica', 'Jamaika', 'Giamaica ', 'JM',  'JAM','388'  ),
('Bailiwick of Jersey ', 'Jersey', 'Jersey', 'Baliato di Jersey', 'JE',  'JEY','832'  ),
('Jordan', 'Jordania', 'Jordanien', 'Giordania', 'JO',  'JOR','400'  ),
('Japan', 'Japon', 'Japan', 'Giappone', 'JP',  'JPN','392'  ),
('Kazakhstan ', 'Kazajistan', 'Kasachistan', 'Kazakistan', 'KZ',  'KAZ','398'  ),
('Kenya', 'Kenia', 'Kenia', 'Kenya', 'KE',  'KEN','404'  ),
('Kyrgyzstan ', 'Kirguistan', 'Kirghizistan', 'Kirghizistan', 'KG',  'KGZ','417'  ),
('Cambodia', 'Camboya', 'Kambodscha', 'Cambogia', 'KH',  'KHM','116'  ),
('Kiribati Republic', 'Kiribati', 'Republik Kiribati', 'Repubblica di Kiribati', 'KI',  'KIR','296'  ),
('St. Kitts and Nevis', 'San Cristobal y Nieves', 'St. Kitts und Nevis', 'Saint Kitts e Nevis', 'KN',  'KNA','659'  ),
('South Korea', 'Corea del Sur', 'Sdkorea', 'Corea del Sud', 'KR',  'KOR','410'  ),
('Kuwait', 'Kuwait', 'Kuwait', 'Kuwait', 'KW',  'KWT','414'  ),
('Laos', 'Laos', 'Laos', 'Laos', 'LA',  'LAO','418'  ),
('Lebanon', 'Libano', 'Libanon', 'Libano', 'LB',  'LBN','422'  ),
('Liberia', 'Liberia', 'Liberia', 'Liberia', 'LR',  'LBR','430'  ),
('Libya', 'Libia', 'Libyen', 'Libia', 'LY',  'LBY','434'  ),
('St.Lucia', 'Santa Lucia', 'St.Lucia', 'Santa Lucia', 'LC',  'LCA','662'  ),
('Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'LI',  'LIE','438'  ),
('Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'LK',  'LKA','144'  ),
('Lesotho', 'Lesoto', 'Lesotho', 'Lesotho', 'LS',  'LSO','426'  ),
('Lithuania', 'Lituania', 'Litauen', 'Lituania', 'LT',  'LTU','440'  ),
('Luxembourg', 'Luxemburgo', 'Luxemburg', 'Lussemburgo', 'LU',  'LUX','442'  ),
('Latvia', 'Letonia', 'Lettland', 'Lettonia', 'LV',  'LVA','428'  ),
('Macao', 'Macao', 'Macau', 'Macao', 'MO',  'MAC','446'  ),
('Collectivity of Saint Martin ', 'San Martin (Francia)', 'Saint Martin', 'Saint Martin', 'MF',  'MAF','534'  ),
('Morocco', 'Marruecos', 'Marokko', 'Marocco', 'MA',  'MAR','504'  ),
('Monaco', 'Monaco', 'Monaco', 'Monaco', 'MC',  'MCO','492'  ),
('Molvoda ', 'Moldavia', 'Moldawien', 'Moldavia', 'MD',  'MDA','498'  ),
('Madagascar', 'Madagascar', 'Madagaskar', 'Madagascar', 'MG',  'MDG','450'  ),
('Maldives', 'Maldivas', 'Malediven', 'Maldive', 'MV',  'MDV','462'  ),
('Mexico', 'Mexico', 'Mexiko', 'Messico', 'MX',  'MEX','484'  ),
('Marshall Islands', 'Islas Marshall', 'Marshallinseln', 'Isole Marshall', 'MH',  'MHL','584'  ),
('Macedonia', 'Macedonia', 'Mazedonien', 'Macedonia', 'MK',  'MKD','807'  ),
('Mali', 'Mali', 'Mali', 'Mali', 'ML',  'MLI','466'  ),
('Malta', 'Malta', 'Malta', 'Malta', 'MT',  'MLT','470'  ),
('Myanmar', 'Myanmar', 'Myanmar', 'Myanmar', 'MM',  'MMR','104'  ),
('Montenegro ', 'Montenegro', 'Montenegro', 'Montenegro', 'ME',  'MNE','499'  ),
('Mongolia', 'Mongolia', 'Mongolei', 'Mongolia', 'MN',  'MNG','496'  ),
('Northern Mariana Islands', 'Islas Marianas del Norte', 'Nordliche Marianen', 'Isole Marianne Settentrionali ', 'MP',  'MNP','580'  ),
('Mozambique', 'Mozambique', 'Mosambik', 'Mozambico', 'MZ',  'MOZ','508'  ),
('Mauritania', 'Mauritania', 'Mauretanien', 'Mauritania', 'MR',  'MRT','478'  ),
('Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'MS',  'MSR','500'  ),
('Martinique', 'Martinica', 'Martinique', 'Martinica', 'MQ',  'MTQ','474'  ),
('Mauritius', 'Mauricio', 'Mauritius', 'Mauritius', 'MU',  'MUS','480'  ),
('Malawi', 'Malaui', 'Malawi', 'Malawi', 'MW',  'MWI','454'  ),
('Malaysia', 'Malasia', 'Malaysia', 'Malesia', 'MY',  'MYS','458'  ),
('Mayotte ', 'Mayotte', 'Mayotte', 'Mayotte', 'YT',  'MYT','175'  ),
('Namibia', 'Namibia', 'Namibia', 'Namibia', 'NA',  'NAM','516'  ),
('New Caledonia', 'Nueva Caledonia', 'Neukaledonien', 'Nuovo Caledonia ', 'NC',  'NCL','540'  ),
('Niger', 'Niger', 'Niger', 'Niger ', 'NE',  'NER','562'  ),
('Norfolk Island', 'Isla Norfolk', 'Norfolkinseln', 'Isola Norfolk ', 'NF',  'NFK','574'  ),
('Nigeria', 'Nigeria', 'Nigeria', 'Nigeria ', 'NG',  'NGA','566'  ),
('Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua ', 'NI',  'NIC','558'  ),
('Niue', 'Niue', 'Niue', 'Niue ', 'NU',  'NIU','570'  ),
('Netherlands', 'Paises Bajos', 'Niederlande', 'Paesi Bassi', 'NL',  'NLD','528'  ),
('Norway', 'Noruega', 'Norwegen', 'Norvegia ', 'NO',  'NOR','578'  ),
('Nepal', 'Nepal', 'Nepal', 'Nepal', 'NP',  'NPL','524'  ),
('Nauru', 'Nauru', 'Nauru', 'Nauru', 'NR',  'NRU','520'  ),
('New Zealand', 'Nueva Zelanda', ' Neuseeland', 'Nuova Zelanda ', 'NZ',  'NZL','554'  ),
('Oman', 'Oman', 'Oman', 'Oman ', 'OM',  'OMN','512'  ),
('Pakistan', 'Pakistan', 'Pakistan', 'Pakistan ', 'PK',  'PAK','586'  ),
('Panama', 'Panama', 'Panama', 'Panama ', 'PA',  'PAN','591'  ),
('Pitcairn Islands ', 'Islas Pitcairn', 'Pitcairninseln', 'Isole Pitcairn', 'PN',  'PCN','612'  ),
('Peru', 'Peru', 'Peru', 'Per? ', 'PE',  'PER','604'  ),
('Philippines', 'Filipinas', 'Philippinen', 'Filippine ', 'PH',  'PHL','608'  ),
('Palau ', 'Palaos', 'Republik Palau', 'Repubblica di Palau', 'PW',  'PLW','585'  ),
('Papua New Guinea', 'Papua Nueva Guinea', 'Papua-Neuguinea', 'Papua Nuova Guinea ', 'PG',  'PNG','598'  ),
('Poland', 'Polonia', 'Polen', 'Polonia ', 'PL',  'POL','616'  ),
('Puerto Rico', 'Puerto Rico', 'Puerto Rico', 'Porto Rico ', 'PR',  'PRI','630'  ),
('North Korea', 'Corea del Norte', 'Nordkorea', 'Corea del Nord ', 'KP',  'PRK','408'  ),
('Portugal', 'Portugal', 'Portugal', 'Portogallo ', 'PT',  'PRT','620'  ),
('Paraguay', 'Paraguay', 'Paraguay', 'Paraguay ', 'PY',  'PRY','600'  ),
('Palestine ', 'Palestina', 'Staat Palastina', 'Stato di Palestina', 'PS',  'PSE','275'  ),
('French Polynesia', 'Polinesia Francesa', 'Franzosisch-Polynesien', 'Polinesia Francese', 'PF',  'PYF','258'  ),
('Qatar', 'Catar', 'Katar', 'Qatar', 'QA',  'QAT','634'  ),
('Reunion', 'Reunion', 'Wiedersehen', 'Riunione', 'RE',  'REU','638'  ),
('Romania', 'Rumania', 'Rumanien', 'Romania', 'RO',  'ROU','642'  ),
('Russia', 'Rusia', 'Russland', 'Russia', 'RU',  'RUS','643'  ),
('Rwandese Republic', 'Ruanda', 'Ruandische Republik', 'Repubblica del Ruanda', 'RW',  'RWA','646'  ),
('Saudi Arabia', 'Arabia Saudita', 'Saudi-Arabien	', 'Arabia Saudita', 'SA',  'SAU','682'  ),
('Sudan', 'Sudan', 'Sudan', 'Sudan', 'SD',  'SDN','729'  ),
('Senegal', 'Senegal', 'Senegal', 'Senegal', 'SN',  'SEN','686'  ),
('Singapore', 'Singapur', 'Singapur', 'Singapore', 'SG',  'SGP','702'  ),
('South Georgia and the South Sandwich Islands ', 'Islas Georgias y Sandwich del Sur', 'Südgeorgien und die Südlichen Sandwichinseln', 'Georgia del Sud e Isole Sandwich Meridionali', 'GS',  'SGS','239'  ),
('Saint Helena and Ascension Island', 'Santa Elena y la Isla Ascension', 'St. Helena und Ascension Island', 'Sant Elena e l Isola dell Ascensione', 'SH',  'SHN','654'  ),
('Svalbard and Jan Mayen Islands', 'Islas Svalbard y Jan Mayen', 'Spitzbergen und Jan-Mayen-Inseln', 'Isole Svalbard e Jan Mayen', 'SJ',  'SJM','744'  ),
('Solomon Islands', 'Islas Salomon', 'Salomonen', 'Isole Salomone', 'SB',  'SLB','90'  ),
('Sierra Leone', 'Sierra Leona', 'Sierra Leone', 'Sierra Leone', 'SL',  'SLE','694'  ),
('El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'SV',  'SLV','222'  ),
('Republic of San Marino', 'San Marino', 'Republik San Marino', 'Repubblica di San Marino', 'SM',  'SMR','674'  ),
('Somalia', 'Somalia', 'Somalia', 'Somalia', 'SO',  'SOM','706'  ),
('Saint Pierre et Miquelon', 'San Pedro y Miguelon', 'Saint Pierre und Miquelon', 'Saint Pierre et Miquelon', 'PM',  'SPM','666'  ),
('Serbia ', 'Serbia', 'Serbien', 'Repubblica di Serbia', 'RS',  'SRB','688'  ),
('Republic of South Sudan ', 'Sudan del Sur', 'Sudsudan', 'Sudan del Sud', 'SS',  'SSD','728'  ),
('Sao Tome e Principe', 'Santo Tome y Principe', 'Sao Tome und Principe', 'Sao Tom? e Principe', 'ST',  'STP','678'  ),
('Suriname', 'Surinam', 'Suriname', 'Suriname', 'SR',  'SUR','740'  ),
('Slovakia', 'Eslovaquia', 'Slowakei', 'Slovacchia', 'SK',  'SVK','703'  ),
('Slovenia', 'Eslovenia', 'Slowenien', 'Slovenia', 'SI',  'SVN','705'  ),
('Sweden', 'Suecia', 'Schweden', 'Svezia', 'SE',  'SWE','752'  ),
('Swaziland', 'Suazilandia', 'Swasiland', 'Swaziland', 'SZ',  'SWZ','748'  ),
('Sint Maarten ', 'San Martin (Paises Bajos)', 'Sint Maarten', 'Sint Maarten', 'SX',  'SXM','663'  ),
('Seychelles', 'Seychelles', 'Seychellen', 'Seychelles', 'SC',  'SYC','690'  ),
('Syria', 'Siria', 'Syrien	', 'Siria', 'SY',  'SYR','760'  ),
('Turks', 'Islas Turcas y caicos', 'Trken', 'Turchi', 'TC',  'TCA','796'  ),
('Chad', 'Chad', 'Tschad', 'Ciad', 'TD',  'TCD','148'  ),
('Togolese Republic', 'Togo', 'Togoische Republik', 'Repubblica del Togo', 'TG',  'TGO','768'  ),
('Thailand', 'Tailandia', 'Thailand', 'Thailandia', 'TH',  'THA','764'  ),
('Tajikistan ', 'Tayikistan', 'Tadschikistan', 'Tagikistan', 'TJ',  'TJK','762'  ),
('Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'TK',  'TKL','772'  ),
('Turkmenistan ', 'Turkmenistan', 'Turkmenistan', 'Turkmenistan', 'TM',  'TKM','795'  ),
('East Timor', 'Timor Oriental', 'Osttimor', 'Timor Est', 'TL',  'TLS','626'  ),
('Tonga', 'Tonga', 'Tonga', 'Tonga', 'TO',  'TON','776'  ),
('Trinidad and Tobago', 'Trinidad y Tobago', 'Trinidad und Tobago', 'Trinidad e Tobago', 'TT',  'TTO','780'  ),
('Tunisia', 'Tunez', 'Tunesien', 'Tunisia', 'TN',  'TUN','788'  ),
('Turkey', 'Turquia', 'Truthahn	', 'Tacchino	', 'TR',  'TUR','792'  ),
('Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'TV',  'TUV','798'  ),
('Taiwan', 'Taiwan', 'Taiwan', 'Taiwan	', 'TW',  'TWN','158'  ),
('Tanzania', 'Tanzania', 'Tansania', 'Tanzania', 'TZ',  'TZA','834'  ),
('Uganda', 'Uganda', 'Uganda', 'Uganda', 'UG',  'UGA','800'  ),
('Ukraine', 'Ucrania', 'Ukraine', 'Ucraina', 'UA',  'UKR','804'  ),
('Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'UY',  'URY','858'  ),
('United States of America', 'Estados Unidos de America', 'Vereinigte Staaten von Amerika', 'Stati Uniti d America	', 'US',  'USA','840'  ),
('Uzbekistan ', 'Uzbekistan', 'Republik Usbekistan', 'Repubblica dell Uzbekistan', 'UZ',  'UZB','860'  ),
('Vatican City', 'Vaticano', 'Vatikanstadt', 'Citta del Vaticano', 'VA',  'VAT','336'  ),
('St.Vincent and the Grenadines', 'San Vicente y las Granadinas', 'St.Vincent und die Grenadinen', 'St.Vincent e Grenadine ', 'VC',  'VCT','670'  ),
('Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'VE',  'VEN','862'  ),
('British Virgin Islands', 'Islas Virgenes Britanicas', 'Britische Jungferninseln', 'Isole Vergini britanniche', 'VG',  'VGB','92'  ),
('US Virgin Islands', 'Islas Virgenes de los Estados Unidos', 'US-amerikanische Jungferninseln', 'Isole Vergini americane', 'VI',  'VIR','850'  ),
('Vietnam', 'Vietnam', 'Vietnam', 'Vietnam', 'VN',  'VNM','704'  ),
('Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'VU',  'VUT','548'  ),
('Wallis and Futuna Islands', 'Islas Wallis y Futuna', 'Wallis- und Futuna-Inseln', 'Isole Wallis e Futuna', 'WF',  'WLF','876'  ),
('Western Samoa', 'Samoa', 'West-Samoa', 'Samoa occidentali', 'WS',  'WSM','882'  ),
('Kosovo ', 'Kosovo', ' Republik Kosovo', 'Cossovo', 'XK',  'XKX','153'  ),
('Yemen', 'Yemen', 'Jemen', 'Yemen', 'YE',  'YEM','887'  ),
('South Africa', 'Sudafrica', 'Sdafrika', 'Sudafrica', 'ZA',  'ZAF','710'  ),
('Zambia', 'Zambia', 'Sambia', 'Zambia', 'ZM',  'ZMB','894'  ),
('Zimbabwe', 'Zimbabwe', 'Simbabwe', 'Zimbabwe', 'ZW',  'ZWE','716'  );

/*
SELECT * FROM COUNTRY 
*/